# tasks file for haproxy
---
- name: 'Add haproxy apt repo (squeeze)'
  apt_repository:
    repo: deb http://http.debian.net/debian {{ ansible_distribution_release }}-backports-sloppy main
    state: present
    update_cache: yes
  when: ansible_distribution_release == 'squeeze'
  tags:
    - haproxy-install-add-repository
    
- name: Add haproxy apt repo (wheezy/jessie)
  apt_repository:
    repo: deb http://http.debian.net/debian {{ ansible_distribution_release }}-backports main
    state: present
    update_cache: yes
  when: ansible_distribution_release == 'wheezy' or ansible_distribution_release == 'jessie'
  tags:
    - haproxy-install-add-repository

- name: Install HAProxy (apt squeeze)
  apt:
    name: "{{ haproxy_package_name }}"
    default_release: "{{ansible_distribution_release}}-backports-sloppy"
  when: ansible_distribution_release == 'squeeze'
  tags:
    - haproxy-install-add-repository

- name: Install HAProxy (apt wheezy/jessie)
  apt:
    name: "haproxy"
    default_release: "{{ansible_distribution_release}}-backports"
  when: ansible_distribution_release == 'wheezy' or ansible_distribution_release == 'jessie'
  tags:
    - haproxy-install-add-repository

- name: Install HAProxy (apt stretch)
  apt:
    name: "haproxy"
    default_release: "{{ansible_distribution_release}}"
  when: ansible_distribution_release == 'stretch'
  tags:
    - haproxy-install-add-repository

- name: install | dependencies
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ haproxy_dependencies }}"
  tags:
    - haproxy-install-dependencies

- name: install | additional
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
  with_items: "{{ haproxy_install }}"
  tags:
    - haproxy-install-additional
