---
- name: Run dlg-web-app
  docker_container:
    name: dlg-web-app
    image: "{{ dlg_web_app_image }}"
    pull: yes
    state: started
    restart: yes
    ports:
      - "{{ dlg_web_app_port }}:80"
  tags: dlg-web-app

- name: Run dlg-invites
  docker_container:
    name: dlg-web-app
    image: "{{ dlg_web_app_image }}"
    pull: yes
    state: started
    restart: yes
    env: "{{ dlg_invites_envs }}"
    ports:
      - "{{ dlg_invites_port }}:8080"
    tags: dlg-invites

- name: Run dlg-dashboard
  docker_container:
    name: dlg-dashboard
    image: "{{ dlg_dashboard_image }}"
    pull: yes
    state: started
    restart: yes
    env: "{{ dlg_dashboard_envs }}"
    ports:
      - "{{ dlg_dashboard_port }}:3000"
  tags: dlg-dashboard-app
