---
- hosts: postgresql
- hosts: pg-master
  become: true
  roles:
    - role: postgres
- hosts: pg-slave
  become: true
  roles:
    - role: postgres
      postgresql_init_slave: true

- hosts: cassandra
  become: true
  roles:
    - role: cassandra
