---
- hosts: dialog-servers
- hosts: postgresql

- hosts: pg-master
  become: true
  roles:
    - role: postgres
      postgresql_pg_hba_custom:
        - { type: host,
            database: "{{ pg_dialog_db }}",
            user: "{{ pg_dialog_user }}",
            address: "{{ hostvars[groups['dialog-servers'][0]]['ansible_default_ipv4']['address'] }}/32",
            method: "md5" }

- hosts: pg-slave
  become: true
  roles:
    - role: postgres
      postgresql_init_slave: true

- hosts: cassandra
  strategy: free
  become: true
  roles:
    - role: cassandra

- hosts: etcd-masters
  become: true
  roles:
    - role: etcd-cluster
      etcd_master_group_name: etcd-masters
      etcd_cluster_name: dlg-etcd
      etcd_secure: false
      when: dlg_cluster
- hosts: etcd-lb
  become: true
  roles:
    - role: haproxy
      haproxy_frontend:
        - name: tcp
          bind:
            - listen: ':2378'
          mode: http
          default_backend: etcd
      haproxy_backend:
        - name: etcd
          mode: http
          balance: roundrobin
          servers_group:
            - name: "etcd"
              group: "{{ groups['etcd'] }}"
              port: 2379
              param:
                - check
      when: dlg_cluster

- hosts: dialog-servers
  become: true
  roles:
    - role: dlg-server
      project_name: "My ee"
      dlg_custom_conf:
        session.idle-timeout: 5 minutes
        modules.sequence.weak-history-updates: true
        akka.log-dead-letters-during-shutdown: off
        modules.presence.deliver-state-interval: 10m
        modules.sequence.max-difference-size: 300 KiB
        modules.runtime.delivery.max-interval: 5 minutes
        akka.http.client.parsing.max-response-reason-length: 2048
        akka.actor.default-dispatcher.fork-join-executor.parallelism-min: 128
        akka.actor.default-dispatcher.fork-join-executor.parallelism-max: 500
      # TODO
      # postgres_hosts: "{{groups['postgres']}}"
      # cassandra_hosts: "{{groups['cassandra']}}"

- hosts: endpoints
  become: true
  roles:
    - role: haproxy
      haproxy_frontend:
        - name: tcp
          bind:
            - listen: ':9970'
          mode: tcp
          default_backend: tcp_dlg
      haproxy_backend:
        - name: tcp_dlg
          mode: tcp
          balance: roundrobin
          servers_group:
            - name: "tcp_dlg"
              group: "{{ groups['dialog-servers'] }}"
              port: 9070
              param:
                - check
            # - name: "dlg-stg"
            #   group: "{{ groups['dialog-servers'] }}"
            #   port: 9070
            #   param:
            #     - check
            #     - param
          # server:
          #   - name: "dlg-server-1"
          #     listen: "1.2.3.4:9070"
          #     param:
          #       - check
