---
dlg_server_home_path: "/opt/dlg-server"
dlg_server_conf_path: "{{ dlg_server_home_path }}/conf"
dlg_server_image: ""

crypto_server_secret: "e4347bb04818d16a47f6fb2926632906f4498d74e859e9c4b1eee74524fb0302" # public demo
crypto_server_public: "8f75fadf7562db90153ecf698d185381b41dcc1f0b7d76f66aef15a3fbfad60c" # public demo

# SMTP
smtp_use: false #true/false dynamic matched
smtp_host: ""
smtp_port: ""
smtp_from: ""
smtp_user: ""
smtp_password: ""
smtp_tls:

# AD
ad_use: false #true/false dynamic matched
ad_host: ""
ad_port: ""
ad_domain: ""
ad_user: ""
ad_password: ""
ad_sync: "10s"

# S3
aws_use: false #true/false dynamic matched
aws_endpoint: ""
aws_bucket: ""
aws_access: ""
aws_secret: ""

# Activation providers
activation_enable: false
dummy_providers: true
sms_provider: "infobip"
sms_providers:
  infobip: "im.dlg.server.auth.activation.infobip.InfoBipProvider"
  telesign: "im.dlg.server.auth.activation.telesign.TelesignProvider"
dummy_provider: "im.dlg.server.auth.activation.dummy.DummyActivationProvider"
smtp_provider: "im.dlg.server.auth.activation.smtp.SMTPProvider"

# infobip if infobip provider
infobip_username: "username"
infobip_password: "password"
infobip_from: "{{ project_name }}"
infobip_template: "Your {{ project_name }} activation code is $$CODE$$"

# telesign if telesign provider
telesign_customer_id: ""
telesign_api_key: ""

# Databases
history_storage: "postgresql"
sequence_storage: "cassandra"
persistence_journal: "cassandra-journal"
persistence_snapshot: "cassandra-snapshot-store"
contacts_storage: "cassandra"
access_interval_storage: "cassandra"
message_status_storage: "cassandra"

# PG
pg_host: "{{ pg_dialog_host }}"
pg_port: "{{ pg_dialog_port }}"
pg_numThreads: 16

# Cassandra
# runtime append from group
#cass_contact_points:
#  - "{{ groups['cassandra'] }}"

# Logging
logstash_host: "logstash.example.com"
environment: "unknown"
