---
- include: install-debian.yml
  tags: [cassandra, cassandra-install]

- include: configure.yml
  tags: [cassandra, cassandra-config]

#- include: service.yml
#  tags: [cassandra, cassandra-service]

- name: Force restart
  service:
    name: cassandra
    state: restarted
