- name: Stop PostgreSQL
  service:
    name: "{{ postgresql_daemon }}"
    state: stopped

- name: Set first replicated flag
  stat:
    path: /var/lib/postgresql/repl_bk
  register: rep_was

- name: Create backup data dir on slave
  file:
    path: /var/lib/postgresql/repl_bk
    state: directory
  when: not rep_was.stat.exists

- name: Backup data dir on slave
  shell: "mv {{ postgresql_data_dir }}/* /var/lib/postgresql/repl_bk"
  when: rep_was.stat.exists

#- name: Clear out data directory
#  shell: "rm -rf {{ postgresql_data_dir }}"/*
