- name: Stop PostgreSQL
  service:
    name: "{{ postgresql_daemon }}"
    state: stopped

- name: Set first replicated flag
  stat:
    path: /var/lib/postgresql/repl_bk
  register: main_dir_bk

- set_fact:
    rep_was: true
  when: main_dir_bk.stat.exists

- name: Create backup data dir on slave
  file:
    path: /var/lib/postgresql/repl_bk
    state: directory
  when: not rep_was

- name: Backup data dir on slave
  shell: "mv {{ postgresql_data_dir }}/* /var/lib/postgresql/repl_bk"
  when: not rep_was

- name: Create base backup
  shell: "su postgres -c 'pg_basebackup -P -R -X stream -h {{ hostvars[groups['pg-master'][0]]['ansible_default_ipv4']['address'] }} -D {{ postgresql_data_dir }} -U {{ postgresql_rep_user }}'"
  when: not rep_was
  #become: yes
  #become_user: postgres

- name: Stop PostgreSQL
  service:
    name: "{{ postgresql_daemon }}"
    state: started
