project_name: "My EE"
base_url: "example.com"
server_license: "BIFBAAJAAEUMDYVF2ACREQAHENY2VNF23TZH6VHIH5EIQJ7ZHJV3XYSNIIQDQCA7PAC4LO642SDECLWKSOKIZ7FQKEENSB3ZBGTXY6LEMIQED5OIVRJM6E3FYI5Q4==="

pg_dialog_user: dialog
pg_dialog_password: dialog
pg_dialog_db: dialog

cassandra_dialog_user: dialog
cassandra_dialog_password: dialog
cassandra_dialog_db: dialog

http_scheme: "http"
tcp_scheme: "tcp"
ws_scheme: "ws"
