project_name: "My Dialog"
base_url: "example.com"

api_uri: "{{ base_url }}"
dashboard_uri: "{{ base_url }}"


mobile_port: 9970
desktop_port: 9980
ssl_mobile_port: 7443
ssl_desktop_port: 8443

pg_dialog_user: dialog
pg_dialog_password: dialog
pg_dialog_db: dialog
pg_dialog_host: "{{ hostvars[groups['pg-master'][0]]['ansible_default_ipv4']['address'] }}"
pg_dialog_port: 6432

cassandra_dialog_user: dialog
cassandra_dialog_password: dialog
cassandra_dialog_db: dialog

http_scheme: "http"

# Private registry
docker_registry: "dialog-docker-registry.bintray.io"
docker_user: ""
docker_password: ""
