nginx_dialog_extra: |
  location / {
    proxy_read_timeout        30s;
    proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass                http://localhost:{{ web_app_port }};
  }
  location /dash {
    proxy_set_header          Host {{ base_url }};
    rewrite                   ^/dash$ {{ http_scheme }}://{{ base_url }}/dash/ permanent;
    rewrite                   ^/dash/(.*) /$1 break;
    proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass                http://localhost:{{ dashboard_port }}/;
  }
  location /config {
    proxy_set_header          Host {{ base_url }};
    proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass                http://localhost:{{ dashboard_port }};
  }
  location /v1 {
    proxy_set_header          Host {{ base_url }};
    proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass                http://{{ dlg_api_uri }}:{{ dlg_api_port }};
  }
  location /api {
    proxy_set_header          Host {{ base_url }};
    proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass                http://{{ dlg_api_uri }}:{{ dlg_api_port }};
  }

nginx_api_dialog_extra: |
  resolver                8.8.4.4 8.8.8.8 valid=300s;
  resolver_timeout        10s;
  proxy_set_header        Host $http_host;
  proxy_set_header        X-Scheme $scheme;
  proxy_set_header        X-Frame-Options DENY;
  proxy_set_header        X-Real-IP $remote_addr;
  proxy_set_header        X-Content-Type-Options nosniff;
  proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;

  location / {
    proxy_read_timeout    30s;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass            http://localhost:8080;
  }
